--
-- File generated with SQLiteStudio v3.3.3 on qua out 19 20:59:46 2022
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: COMPRA
CREATE TABLE COMPRA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	TOTAL DOUBLE NULL,
	QUANTIDADE INTEGER NULL
);

-- Table: ESTOQUE
CREATE TABLE ESTOQUE (
	ID INTEGER NOT NULL PRIMARY KEY,
	IDPRODUTO INTEGER NOT NULL REFERENCES PRODUTO(ID),
	QUANTIDADE INTEGER NULL,
	VALORUNITARIO DOUBLE NULL,
    DATALOTE DATE NULL
);

-- Table: FARMACIA
CREATE TABLE FARMACIA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	IDCOMPRA INTEGER NOT NULL REFERENCES COMPRA(ID),
	NOME STRING(250)
);

-- Table: PRODUTO
CREATE TABLE PRODUTO (
	ID INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NULL,
	VALIDADE DATE NULL
);

-- Table: RESERVA
CREATE TABLE RESERVA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	IDCOMPRA INTEGER NOT NULL REFERENCES COMPRA(ID),
	NOME VARCHAR(250) NULL,
	DATA DATE NULL,
	QUANTIDADE INTEGER NULL
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
