CREATE DATABASE farmacia;

USE farmacia;

CREATE TABLE PRODUTO (
	ID INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(250) NULL,
	VALIDADE DATE NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE ESTOQUE (
	ID INT NOT NULL AUTO_INCREMENT,
	IDPRODUTO INT NOT NULL,
	QUANTIDADE INT NULL,
	VALORUNITARIO DOUBLE NULL,
    DATALOTE DATE NULL,
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(ID),
    CONSTRAINT PK_ESTOQUE PRIMARY KEY (ID)
);

CREATE TABLE COMPRA (
	ID INT NOT NULL AUTO_INCREMENT,
    IDESTOQUE INT NOT NULL,
	TOTAL DOUBLE NULL,
	QUANTIDADE INT NULL,
    FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE(ID),
    CONSTRAINT PK_COMPRA PRIMARY KEY (ID)
);

CREATE TABLE RESERVA (
	ID INT NOT NULL AUTO_INCREMENT,
    IDESTOQUE INT NOT NULL,
	IDCOMPRA INT NOT NULL,
	NOME VARCHAR(250) NULL,
	DATA DATE NULL,
	QUANTIDADE INT NULL,
    FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE(id),
    FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA(ID),
    CONSTRAINT PK_RESERVA PRIMARY KEY (id)
);

CREATE TABLE FARMACIA (
	ID INT NOT NULL AUTO_INCREMENT,
	IDESTOQUE,
	IDCOMPRA,
	NOME
);