CREATE TABLE PRODUTO (
	ID INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NULL,
	VALIDADE DATE NULL
);

CREATE TABLE ESTOQUE (
	ID INTEGER NOT NULL PRIMARY KEY,
	IDPRODUTO INTEGER NOT NULL REFERENCES PRODUTO(ID),
	QUANTIDADE INTEGER NULL,
	VALORUNITARIO DOUBLE NULL,
    DATALOTE DATE NULL
);

CREATE TABLE COMPRA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	TOTAL DOUBLE NULL,
	QUANTIDADE INTEGER NULL
);

CREATE TABLE RESERVA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	IDCOMPRA INTEGER NOT NULL REFERENCES COMPRA(ID),
	NOME VARCHAR(250) NULL,
	DATA DATE NULL,
	QUANTIDADE INTEGER NULL
);
CREATE TABLE FARMACIA (
	ID INTEGER NOT NULL PRIMARY KEY,
    IDESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID),
	IDCOMPRA INTEGER NOT NULL REFERENCES COMPRA(ID),
	NOME STRING(250)
);